@hostname = http://localhost
@port = 8080
@host = {{hostname}}:{{port}}
@version= v2
@contentType = application/json
@token = {{$dotenv TOKEN}}

@testWalletAddress = 0x524bF2086D4b5BBdA06f4c16Ec36f06AAd4E1Cad
@testWalletAddress2 = 0xD7029BDEa1c17493893AAfE29AAD69EF892B8ff2
@testGroupId = 5851f119fc7c2fd151c1e174f221fb4d

###
GET {{host}}/{{version}}/wallets/{{testWalletAddress}} HTTP/1.1
Authorization: Bearer {{token}}

### 
# adds a group member
PATCH {{host}}/{{version}}/groups/{{testGroupId}}/members HTTP/1.1
Authorization: Bearer {{token}}
content-type: application/json

{
  "members": ["{{testWalletAddress2}}"]
}

###
GET {{host}}/{{version}}/wallets/{{testWalletAddress2}}/sync HTTP/1.1

###
POST {{host}}/{{version}}/group/c68c8e59018b46484f0b365f1e48056a/members HTTP/1.1
content-type: application/json

{
  "type": "add",
  "members": ["0xD452ba2fB26fB7b529178b3fa4B96b2719ca8D46"]
}

###
GET {{host}}/{{version}}/bot/sync-members HTTP/1.1

###
GET {{host}}/{{version}}/bot/retry-pending-members HTTP/1.1

###
GET {{host}}/{{version}}/bot/sync-pending-members?groupId=c6894e8dae94456ef19fb2fcf1bbbdec HTTP/1.1
