POST http://localhost:8080/bot/create HTTP/1.1
content-type: application/json

{
  "groupAddress": "sep:0x76e009080E15DfbBF9a8424dB2D5b6772b6B5341"
}

###
POST http://localhost:8080/bot/create HTTP/1.1
content-type: application/json

{
  "groupType": "safe",
  "groupAddress": "0x76e009080E15DfbBF9a8424dB2D5b6772b6B5341"
}

###
POST http://localhost:8080/bot/create HTTP/1.1
content-type: application/json

{
  "members": ["0xD452ba2fB26fB7b529178b3fa4B96b2719ca8D46"]
}

###
GET http://localhost:8080/bot/safe/1 HTTP/1.1

###
GET http://localhost:8080/bot/safe/10 HTTP/1.1

###
GET http://localhost:8080/bot/sync-pending-members HTTP/1.1

###
GET http://localhost:8080/group/1 HTTP/1.1

###
GET http://localhost:8080/group/4cf971dcb124e9e57fad653cdc6242f1 HTTP/1.1

###
GET http://localhost:8080/group/4cf971dcb124e9e57fad653cdc6242f1/members HTTP/1.1


###
GET http://localhost:8080/group/4cf971dcb124e9e57fad653cdc6242f1/wallets HTTP/1.1

